code/dure/config/routes.rb
Rails.application.routes.draw do
  resources :duers
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

code/dure/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

code/dure/app/models/duer.rb
class Duer < ApplicationRecord
  has_many :workunits
end

code/dure/app/models/risk.rb
class Risk < ApplicationRecord
  belongs_to :workunit
  has_many :underrisks
end

code/dure/app/models/underrisk.rb
class Underrisk < ApplicationRecord
  belongs_to :risk
end

code/dure/app/models/workunit.rb
class Workunit < ApplicationRecord
  belongs_to :duer
  has_many :risks
end

code/dure/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

code/dure/app/controllers/duers_controller.rb
class DuersController < ApplicationController
  before_action :set_duer, only: [:show, :edit, :update, :destroy]

  # GET /duers
  # GET /duers.json
  def index
    @duers = Duer.all
  end

  # GET /duers/1
  # GET /duers/1.json
  def show
  end

  # GET /duers/new
  def new
    @duer = Duer.new
  end

  # GET /duers/1/edit
  def edit
  end

  # POST /duers
  # POST /duers.json
  def create
    @duer = Duer.new(duer_params)

    respond_to do |format|
      if @duer.save
        format.html { redirect_to @duer, notice: 'Duer was successfully created.' }
        format.json { render :show, status: :created, location: @duer }
      else
        format.html { render :new }
        format.json { render json: @duer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /duers/1
  # PATCH/PUT /duers/1.json
  def update
    respond_to do |format|
      if @duer.update(duer_params)
        format.html { redirect_to @duer, notice: 'Duer was successfully updated.' }
        format.json { render :show, status: :ok, location: @duer }
      else
        format.html { render :edit }
        format.json { render json: @duer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /duers/1
  # DELETE /duers/1.json
  def destroy
    @duer.destroy
    respond_to do |format|
      format.html { redirect_to duers_url, notice: 'Duer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_duer
      @duer = Duer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def duer_params
      params.require(:duer).permit(:name, :activity, :address, :effective, :other)
    end
end

code/dure/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

code/dure/app/helpers/application_helper.rb
module ApplicationHelper
end

code/dure/app/views/duers/_form.html.erb
<%= simple_form_for(@duer) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :activity %>
    <%= f.input :address %>
    <%= f.input :effective %>
    <%= f.input :other %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

code/dure/app/views/duers/edit.html.erb
<h1>Editing Duer</h1>

<%= render 'form', duer: @duer %>

<%= link_to 'Show', @duer %> |
<%= link_to 'Back', duers_path %>

code/dure/app/views/duers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Duers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Activity</th>
      <th>Address</th>
      <th>Effective</th>
      <th>Other</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @duers.each do |duer| %>
      <tr>
        <td><%= duer.name %></td>
        <td><%= duer.activity %></td>
        <td><%= duer.address %></td>
        <td><%= duer.effective %></td>
        <td><%= duer.other %></td>
        <td><%= link_to 'Show', duer %></td>
        <td><%= link_to 'Edit', edit_duer_path(duer) %></td>
        <td><%= link_to 'Destroy', duer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Duer', new_duer_path %>

code/dure/app/views/duers/new.html.erb
<h1>New Duer</h1>

<%= render 'form', duer: @duer %>

<%= link_to 'Back', duers_path %>

code/dure/app/views/duers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @duer.name %>
</p>

<p>
  <strong>Activity:</strong>
  <%= @duer.activity %>
</p>

<p>
  <strong>Address:</strong>
  <%= @duer.address %>
</p>

<p>
  <strong>Effective:</strong>
  <%= @duer.effective %>
</p>

<p>
  <strong>Other:</strong>
  <%= @duer.other %>
</p>

<%= link_to 'Edit', edit_duer_path(@duer) %> |
<%= link_to 'Back', duers_path %>

code/dure/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

code/dure/app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>